
### obteniendo el litado de publicaciones
 GET http://localhost:3000/api/users

### obteniendo el litado de movies
GET http://localhost:3000/api/movies


### Agregando un nuevo registro
 POST http://localhost:3000/api/movies
 Content-Type: application/json

 {
   "titulo": "gato con botas",
    "director": "patricio aguayo",
    "year": "1990",
    "rating": "9"
}

### actualizando un registro de movies
 
 PUT http://localhost:3000/api/movies/3
 Content-Type: application/json

  {
   "titulo": "gato con botas",
    "director": "patricio aguayo",
    "year": "1990",
    "rating": "8"
}


### eliminado un registro de movies
 
 DELETE http://localhost:3000/api/movies/1
 Content-Type: application/json

